// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AlertController from "./alert_controller"
application.register("alert", AlertController)

import EditListController from "./edit_list_controller"
application.register("edit-list", EditListController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LoadActorsController from "./load_actors_controller"
application.register("load-actors", LoadActorsController)

import LoadMoreController from "./load_more_controller"
application.register("load-more", LoadMoreController)

import RefreshListController from "./refresh_list_controller"
application.register("refresh-list", RefreshListController)

import TypedJsController from "./typed_js_controller"
application.register("typed-js", TypedJsController)
